### ISSUE TITLE
테스트 케이스 작성

### ISSUE THREAD

**Issue by bluing87** [hijang/lsc_cctv#30]
테스트 케이스 작성

**Comment by saddopop** [comment]
test cases - https://docs.google.com/document/d/1QmL_wjV0KDQuBUlXgHG1L1XTvI0lyvjRcbo6NflI36M/edit?usp=sharing

**Comment by hijang** [comment]
통신 구간 암호화와 관련된 내용을 확인하는 테스트 케이스가 없는것 같습니다. 확인하신 후 누락되었다면, 해당 케이스를 추가한 다음 다시 close 부탁 드립니다

**Comment by bluing87** [comment]
통신을 위해 사용하는 포트가 SSL 및 TLS를 사용하는 포트인지 확인하는 TC를 추가하였습니다.

Add new test TC for checking that fixed port is reserved for ssl/tls.
