### ISSUE TITLE
Set up to run CCTV on background using systemd.

### ISSUE THREAD

**Issue by bluing87** [hijang/lsc_cctv#33]
Set up to run CCTV on background using systemd.

**Comment by tehloo** [comment]
Clone source files to /home/cctv/work/lsc_cctv and build it as installation.

**Comment by tehloo** [comment]
- Make a script to run cctv binary 4ea614297c8c100e4c341581c9c761f36fab063c
- Move the binary to root dir 981ac1771852722e6fd6f57a321b513c2fb20897

**Comment by tehloo** [comment]
### How to deploy
1. Make a symbolic link for cctv.sh on HOME dir (ig, /home/cctv/cctv.sh)
2. /etc/systemd/system/cctv.service is invoke the script as `ExecStart=/home/cctv/cctv.sh`
3. reload systemd daemon and enable service
```
$ sudo systemctl daemon-reload
```
4. start the service
```
$ sudo systemctl start cctv
```
5. get status of the service
6. get log for the service

**Comment by tehloo** [comment]
- return code as it gets from executed binary to let systemd restart the service on crash things... 75110ce29ca0f47f66d1b5db2b5ae0bc55e6780e

**Comment by tehloo** [comment]
Make dependancy to `/etc/systemd/system/nvargus-daemon.service` for stop or restart of cctv

```
[Unit]
Description=Argus daemon
...
PartOf=cctv.service
```
**It needs to be discussed whether include it or not**

**Comment by tehloo** [comment]
Confirm running with systemd. close.
