### ISSUE TITLE
apply ACLs to CCTV 

### ISSUE THREAD

**Issue by hijang** [hijang/lsc_cctv#39]
CCTV에 적용되어야 하는 ACL 정책을 반영해야 한다.
ACL 정책 반영 후 보안 요구사항을 만족하는지 확인해야 한다.

또한, 배포시 활용할 수 있도록 ACL 정책을 반영하는 작업을 script로 자동화하거나 매뉴얼화 해야 한다.

**Comment by saddopop** [comment]
Apply ACLs to the following assets
- CCTV logs
- CCTV photo images
- User Register tool
