### ISSUE TITLE
Logging for non-repudiation

### ISSUE THREAD

**Issue by saddopop** [hijang/lsc_cctv#4]
1. Log usage
1.1 Examples of use
 #include "logger.h"
 void main(void)
 {
     ....
     logg.fatal("new person");
     logg.error("connection fail");
     logg.trace("known person");
    logg.info("connected");
     ....
 }
1.2  Log category
 `-`  fatal : A serious security error occurs, so the log is saved and output to the console window
 `-` error : when a problem occurs during processing or security error occurs
 `-` info : write informational messages such as status, code debugging information, etc.
 `-` trace : records about server room entry/exit
1.3 Log file path
`-` LgFaceRecDemoTCP_Jetson_NanoV2/build/YYYYMMDD.log
1.4 Components of Log
`-` [header] [Time Stamp] [[FUNCTION: LINE]] : [some comments of type string]
ex) [INFO]  Jun/14/2021 11:15:06 [main:9] : connected

2. Features
2.1 Record access history to server room
`2.1.1` Logging the number of new people in and out the server room in every frame.
`2.1.2` Logging the known person who is entry and exit the server room.
`2.1.2.1` To set the hysteresis to 10 to reduce the number of records that recognize noisy data that is constantly transitioning between new and known people.
2.2 Connection status record between monitoring system and CCTV
`2.2.1` connection pass/fail시
3.

**Comment by dh-edu** [comment]
1.1.2.1 new person과 known person을 왔다 갔다하는 노이즈성 데이터가 기록되는 횟수를 낮추기 위해 히스테리시스를 10으로 잡음.

- 히스테리시스가 너무 낮을 경우 부정확한 노이즈성 데이터가 로그에 많이 남을 수 있음
- 히스테리스스가 너무 높으면 짧은 시간에 입출입이 발생할 때의 데이터를 놓칠 수 있음.
=>  적정한 수준의 히스테리시스값이 필요

@히스테리시스를 10으로 잡은 이유 
- 카메라를 구동시켜서 1초동안 로깅되는 횟수를 파악
: 7-10개 frame이 로깅된다.
- 사람이 빠르게 움직였을때 1초정도 걸릴 것으로 가정
=> 히스테리시스를 10으로 정함

**Comment by dh-edu** [comment]
로그 파일의 사이즈가 너무 커지면 문제가 될 수 있을 것 같음

**Comment by dh-edu** [comment]
log 파일의 path가 현재는 build 아래 생성되는데, 폴더 path를 정해서 접근할 수 있는 권한을 제한해야 할 것 같음
