### ISSUE TITLE
user register툴 구현

### ISSUE THREAD

**Issue by saddopop** [hijang/lsc_cctv#5]

**Comment by hijang** [comment]
아래의 기능까지 User Register에 구현해야 한다.

## The Monitoring system manager can access CCTV and unregister an Authorized Person.

### Use case 3-1
User: a monitoring system manager

Preconditions: 
* Having a list of people to exclude from Authorized Person
* The monitoring system manager logged into CCTV via ssh

Primary Flow
1. The monitoring system manager executes the User Register with the name of the person to be excluded from the Authorized Person as an argument.
2. The User Register deletes photos in secured storage.
3. The monitoring system manager logs out of ssh.

Alternative Flow
1. The system manager executes User Register with a name not included in Authorized Person as an argument.
2. User Register displays a message saying that the name does not exist.
3. The monitoring system manager tries the contents of the Primary Flow again.

**Comment by hijang** [comment]
https://github.com/hijang/lsc_cctv/issues/15

이슈의 변경까지 반영하여 테스트 후 close 예정

**Comment by hijang** [comment]
어제 동작을 확인했음
