### ISSUE TITLE
Key invoke failed

### ISSUE THREAD

**Issue by chj1986** [hijang/lsc_cctv#55]
To register user at server I excute UserRegister and after that cctv didn't work
Log message is displayed like below : 

keyctl_link: Key has been revoked
request key error. load in source code instead.
[FATAL] Jun/21/2021 19:26:42 [main:119] : Loading server certification and private key is fail

Fail to start service [Internal Error : Load server cert/key is failed.

=> Key registerd 
cctv@LgFaceRecProject:~/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build$ keyctl list @u
4 keys in keyring:
793941548: --alswrv  1006  1006 user: server_crt
141149183: --alswrv  1006  1006 user: fnk
449907822: --alswrv  1006  1006 user: fk
 44998139: --alswrv  1006  1006 user: server_key

**Comment by bluing87** [comment]
Is cctv launched by systemd??
Could you check cctv after rebooting after finishing setting system?
cctv can work and read key well after launching by systemd.

**Comment by chj1986** [comment]
cctv@LgFaceRecProject:~$ systemctl status cctv
● cctv.service - CCTV
   Loaded: loaded (/etc/systemd/system/cctv.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-06-21 20:28:37 EDT; 5min ago
  Process: 25196 ExecStart=/home/cctv/cctv.sh (code=exited, status=139)
 Main PID: 25196 (code=exited, status=139)


-- Logs begin at Sun 2021-06-20 23:55:41 EDT. --
Jun 21 20:23:42 LgFaceRecProject cctv.sh[24808]: END OF cctv.sh with return code 139
Jun 21 20:23:42 LgFaceRecProject cctv.sh[24808]: + exit 139
Jun 21 20:23:42 LgFaceRecProject systemd[1]: cctv.service: Main process exited, code=exited, status=139/n/a
Jun 21 20:23:42 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 21 20:23:47 LgFaceRecProject systemd[1]: cctv.service: Service hold-off time over, scheduling restart.
Jun 21 20:23:47 LgFaceRecProject systemd[1]: cctv.service: Scheduled restart job, restart counter is at 5.
Jun 21 20:23:47 LgFaceRecProject systemd[1]: Stopped CCTV.
Jun 21 20:23:47 LgFaceRecProject systemd[1]: cctv.service: Start request repeated too quickly.
Jun 21 20:23:47 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 21 20:23:47 LgFaceRecProject systemd[1]: Failed to start CCTV.

**Comment by chj1986** [comment]
Used systemd start like below : 
$ sudo systemctl daemon-reload
$ sudo systemctl start cctv

cctv failed with code 139.

**Comment by tehloo** [comment]
Please process 2 steps below

1. [Execute acl.sh on cctv user with sudo previledge.](https://github.com/hijang/lsc_cctv/blob/master/LgFaceRecDemoTCP_Jetson_NanoV2/README.md#7-apply-acls)
2. [Make sure dependency with nvargus-daemon has been set.](https://github.com/hijang/lsc_cctv/blob/master/LgFaceRecDemoTCP_Jetson_NanoV2/README.md#2-set-dependency-to-camera-daemon)

Then reboot the system or restart the cctv service.
If you have a problem, then please attach the log file with command as below.
```
sudo journalctl -u cctv > cctv.log
```

**Comment by chj1986** [comment]
-- Logs begin at Tue 2021-06-22 00:43:41 EDT, end at Tue 2021-06-22 00:46:54 EDT. --
Jun 22 00:45:48 LgFaceRecProject systemd[1]: Started CCTV.
Jun 22 00:45:48 LgFaceRecProject cctv.sh[7372]: + WORKING_DIR=/home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:45:48 LgFaceRecProject cctv.sh[7372]: + cd /home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:45:48 LgFaceRecProject cctv.sh[7372]: + ./LgFaceRecDemoTCP_Jetson_NanoV2
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::GridAnchor_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::NMS_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::Reorg_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::Region_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::Clip_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::LReLU_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::PriorBox_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::Normalize_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::RPROI_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::BatchedNMS_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::FlattenConcat_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::CropAndResize version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::DetectionLayer_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::Proposal version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::ProposalLayer_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::PyramidROIAlign_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::ResizeNearest_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::Split version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::SpecialSlice_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: UNKNOWN: Registered plugin creator - ::InstanceNormalization_TRT version 1
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: request key error. load in source code instead.
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: link user to session keyring
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: [FATAL] Jun/22/2021 00:45:49 [main:119] : Loading server certification and private key is fail
Jun 22 00:45:49 LgFaceRecProject cctv.sh[7372]: Fail to start service [Internal Error : Load server cert/key is failed.
Jun 22 00:45:50 LgFaceRecProject cctv.sh[7372]: SslConnect is deleted!
Jun 22 00:45:50 LgFaceRecProject cctv.sh[7372]: + ret=255
Jun 22 00:45:50 LgFaceRecProject cctv.sh[7372]: + echo 'END OF cctv.sh with return code 255'
Jun 22 00:45:50 LgFaceRecProject cctv.sh[7372]: END OF cctv.sh with return code 255
Jun 22 00:45:50 LgFaceRecProject cctv.sh[7372]: + exit 255
Jun 22 00:45:50 LgFaceRecProject systemd[1]: cctv.service: Main process exited, code=exited, status=255/n/a
Jun 22 00:45:50 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 22 00:45:55 LgFaceRecProject systemd[1]: cctv.service: Service hold-off time over, scheduling restart.
Jun 22 00:45:55 LgFaceRecProject systemd[1]: cctv.service: Scheduled restart job, restart counter is at 1.
Jun 22 00:45:55 LgFaceRecProject systemd[1]: Stopped CCTV.
Jun 22 00:45:55 LgFaceRecProject systemd[1]: Started CCTV.
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: + WORKING_DIR=/home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: + cd /home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: + ./LgFaceRecDemoTCP_Jetson_NanoV2
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::GridAnchor_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::NMS_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::Reorg_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::Region_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::Clip_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::LReLU_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::PriorBox_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::Normalize_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::RPROI_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::BatchedNMS_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::FlattenConcat_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::CropAndResize version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::DetectionLayer_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::Proposal version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::ProposalLayer_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::PyramidROIAlign_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::ResizeNearest_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::Split version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::SpecialSlice_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: UNKNOWN: Registered plugin creator - ::InstanceNormalization_TRT version 1
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: request key error. load in source code instead.
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: link user to session keyring
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: [FATAL] Jun/22/2021 00:45:55 [main:119] : Loading server certification and private key is fail
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: Fail to start service [Internal Error : Load server cert/key is failed.
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: SslConnect is deleted!
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: + ret=255
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: + echo 'END OF cctv.sh with return code 255'
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: END OF cctv.sh with return code 255
Jun 22 00:45:55 LgFaceRecProject cctv.sh[7406]: + exit 255
Jun 22 00:45:55 LgFaceRecProject systemd[1]: cctv.service: Main process exited, code=exited, status=255/n/a
Jun 22 00:45:55 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 22 00:46:00 LgFaceRecProject systemd[1]: cctv.service: Service hold-off time over, scheduling restart.
Jun 22 00:46:00 LgFaceRecProject systemd[1]: cctv.service: Scheduled restart job, restart counter is at 2.
Jun 22 00:46:00 LgFaceRecProject systemd[1]: Stopped CCTV.
Jun 22 00:46:00 LgFaceRecProject systemd[1]: Started CCTV.
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: + WORKING_DIR=/home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: + cd /home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: + ./LgFaceRecDemoTCP_Jetson_NanoV2
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::GridAnchor_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::NMS_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::Reorg_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::Region_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::Clip_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::LReLU_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::PriorBox_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::Normalize_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::RPROI_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::BatchedNMS_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::FlattenConcat_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::CropAndResize version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::DetectionLayer_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::Proposal version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::ProposalLayer_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::PyramidROIAlign_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::ResizeNearest_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::Split version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::SpecialSlice_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: UNKNOWN: Registered plugin creator - ::InstanceNormalization_TRT version 1
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: request key error. load in source code instead.
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: link user to session keyring
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: [FATAL] Jun/22/2021 00:46:00 [main:119] : Loading server certification and private key is fail
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: Fail to start service [Internal Error : Load server cert/key is failed.
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: SslConnect is deleted!
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: + ret=255
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: + echo 'END OF cctv.sh with return code 255'
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: END OF cctv.sh with return code 255
Jun 22 00:46:00 LgFaceRecProject cctv.sh[7493]: + exit 255
Jun 22 00:46:00 LgFaceRecProject systemd[1]: cctv.service: Main process exited, code=exited, status=255/n/a
Jun 22 00:46:00 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 22 00:46:05 LgFaceRecProject systemd[1]: cctv.service: Service hold-off time over, scheduling restart.
Jun 22 00:46:05 LgFaceRecProject systemd[1]: cctv.service: Scheduled restart job, restart counter is at 3.
Jun 22 00:46:05 LgFaceRecProject systemd[1]: Stopped CCTV.
Jun 22 00:46:05 LgFaceRecProject systemd[1]: Started CCTV.
Jun 22 00:46:05 LgFaceRecProject cctv.sh[7577]: + WORKING_DIR=/home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:46:05 LgFaceRecProject cctv.sh[7577]: + cd /home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:46:05 LgFaceRecProject cctv.sh[7577]: + ./LgFaceRecDemoTCP_Jetson_NanoV2
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::GridAnchor_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::NMS_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::Reorg_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::Region_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::Clip_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::LReLU_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::PriorBox_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::Normalize_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::RPROI_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::BatchedNMS_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::FlattenConcat_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::CropAndResize version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::DetectionLayer_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::Proposal version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::ProposalLayer_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::PyramidROIAlign_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::ResizeNearest_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::Split version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::SpecialSlice_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: UNKNOWN: Registered plugin creator - ::InstanceNormalization_TRT version 1
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: request key error. load in source code instead.
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: link user to session keyring
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: [FATAL] Jun/22/2021 00:46:06 [main:119] : Loading server certification and private key is fail
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: Fail to start service [Internal Error : Load server cert/key is failed.
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: SslConnect is deleted!
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: + ret=255
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: + echo 'END OF cctv.sh with return code 255'
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: END OF cctv.sh with return code 255
Jun 22 00:46:06 LgFaceRecProject cctv.sh[7577]: + exit 255
Jun 22 00:46:06 LgFaceRecProject systemd[1]: cctv.service: Main process exited, code=exited, status=255/n/a
Jun 22 00:46:06 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 22 00:46:11 LgFaceRecProject systemd[1]: cctv.service: Service hold-off time over, scheduling restart.
Jun 22 00:46:11 LgFaceRecProject systemd[1]: cctv.service: Scheduled restart job, restart counter is at 4.
Jun 22 00:46:11 LgFaceRecProject systemd[1]: Stopped CCTV.
Jun 22 00:46:11 LgFaceRecProject systemd[1]: Started CCTV.
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: + WORKING_DIR=/home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: + cd /home/cctv/work/lsc_cctv/LgFaceRecDemoTCP_Jetson_NanoV2/build
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: + ./LgFaceRecDemoTCP_Jetson_NanoV2
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::GridAnchor_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::NMS_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::Reorg_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::Region_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::Clip_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::LReLU_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::PriorBox_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::Normalize_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::RPROI_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::BatchedNMS_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::FlattenConcat_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::CropAndResize version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::DetectionLayer_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::Proposal version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::ProposalLayer_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::PyramidROIAlign_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::ResizeNearest_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::Split version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::SpecialSlice_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: UNKNOWN: Registered plugin creator - ::InstanceNormalization_TRT version 1
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: request key error. load in source code instead.
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: link user to session keyring
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: [FATAL] Jun/22/2021 00:46:11 [main:119] : Loading server certification and private key is fail
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: Fail to start service [Internal Error : Load server cert/key is failed.
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: SslConnect is deleted!
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: + ret=255
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: + echo 'END OF cctv.sh with return code 255'
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: END OF cctv.sh with return code 255
Jun 22 00:46:11 LgFaceRecProject cctv.sh[7666]: + exit 255
Jun 22 00:46:11 LgFaceRecProject systemd[1]: cctv.service: Main process exited, code=exited, status=255/n/a
Jun 22 00:46:11 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 22 00:46:16 LgFaceRecProject systemd[1]: cctv.service: Service hold-off time over, scheduling restart.
Jun 22 00:46:16 LgFaceRecProject systemd[1]: cctv.service: Scheduled restart job, restart counter is at 5.
Jun 22 00:46:16 LgFaceRecProject systemd[1]: Stopped CCTV.
Jun 22 00:46:16 LgFaceRecProject systemd[1]: cctv.service: Start request repeated too quickly.
Jun 22 00:46:16 LgFaceRecProject systemd[1]: cctv.service: Failed with result 'exit-code'.
Jun 22 00:46:16 LgFaceRecProject systemd[1]: Failed to start CCTV.

**Comment by chj1986** [comment]
@tehloo I'm sorry, I couldn't upload the log files because of water-wall program.

**Comment by chj1986** [comment]
Execute acl.sh on cctv user with sudo previledge. ==> cctv has sudo previledge and create imgs folder 
(drwx------  2 cctv cctv        4096 Jun 21 20:50 imgs)
Make sure dependency with nvargus-daemon has been set. ==> checked
Then reboot the system or restart the cctv service. ==> after reboot the system, cctv service load failed with return code 255

**Comment by saddopop** [comment]
Sorry to bother you. We are now making a patch for you. Once it is ready, we will get back to you shortly.

**Comment by chj1986** [comment]
@saddopop Thank you! 👍

**Comment by chj1986** [comment]
If possible, I want know how to register new user.
Could you let us know how to do?

**Comment by saddopop** [comment]
Sure. We will let you know how to register a new user when we get back to you.

**Comment by tehloo** [comment]
FYI, bugfix for initial update has been uploaded to another branch 516a2d2ac459cc56124d8538abbe6f405052f60d
which is already fixed on your target manualy.
