### ISSUE TITLE
윈도우쪽 priv 키 관리

### ISSUE THREAD

**Issue by saddopop** [hijang/lsc_cctv#6]
private key를 안전하게 관리하기 위한 대안을 활용하여 제품 '사용' 주기 동안 private key가 노출되지 않도록 한다.

식별된 대안은 아래와 같다. (안전한 순서)
  1. windows 인증서 관리자 도구(Certmgr.exe)를 사용한다.
  2. 특정한 위치에 있는 private key를 암호화하여 보호한다.
  3. private key의 위치 정보를 숨긴다.
 
되도록 안전한 대안을 사용 가능하도록 하는 방법을 찾아서, 선택한 대안을 구현한다.

**Comment by tehloo** [comment]
Code in client side has been restored with 7a3e4cb45179d847fcee1b16e2ba1d3883950f10
