### ISSUE TITLE
Key management on CCTV

### ISSUE THREAD

**Issue by saddopop** [hijang/lsc_cctv#7]
List of Keys for CCTV system
1. Public Key (Authentication)
2. Private Key (Authentication)
3. File encryption Key

Key management and scenario for CCTV
Keys are securely managed through Kernel Key Retention Service.
1. CCTV power on
2. Load encrypted key by systemd
3. CCTV server and encryption tool decrypt encrypted key and apply it for each module

Issues
1. Systemd can not get encrypted key during boot. Known Issue: https://github.com/systemd/systemd/issues/5522
2. Not easy to store a master key securely without HSM.

**Comment by andyincode** [comment]
keyutils version
keyutils-1.5.9 (Built 2018-04-18)

**Comment by tehloo** [comment]
Confirm key has loaded on ubuntu.
